import 'package:instrument_pos/core/database/tables.dart';

/// Read model for a product row (generated by Drift into app_database.dart).
export 'package:instrument_pos/core/database/tables.dart'
    show ProductTrackingType;

/// Form input used to create or update a product.
class ProductDraft {
  const ProductDraft({
    this.id,
    this.sku,
    this.barcode,
    required this.name,
    this.categoryId,
    this.brandId,
    this.description,
    this.costPrice = 0,
    this.sellingPrice = 0,
    this.taxRate = 0,
    this.reorderLevel = 0,
    this.trackingType = ProductTrackingType.quantity,
    this.isActive = true,
  });

  final String? id;
  final String? sku;
  final String? barcode;
  final String name;
  final String? categoryId;
  final String? brandId;
  final String? description;
  final double costPrice;
  final double sellingPrice;
  final double taxRate;
  final double reorderLevel;
  final ProductTrackingType trackingType;
  final bool isActive;
}
